import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    FIREBASE_ADMIN_PROJECT_ID: process.env.FIREBASE_ADMIN_PROJECT_ID || "NAO_DEFINIDA",
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || "NAO_DEFINIDA",
    FIREBASE_ADMIN_CLIENT_EMAIL: process.env.FIREBASE_ADMIN_CLIENT_EMAIL ? "OK" : "NAO_DEFINIDA",
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL ? "OK" : "NAO_DEFINIDA",
    FIREBASE_ADMIN_PRIVATE_KEY: process.env.FIREBASE_ADMIN_PRIVATE_KEY ? "OK" : "NAO_DEFINIDA",
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY ? "OK" : "NAO_DEFINIDA",
  });
}
